// @generated by `cargo xtask wire-js` from ssc-wire's schema. DO NOT EDIT.
// The reviewed decoder/reconciler lives in the hand-written findings.js.

export type WireRuleId =
  | "lex.excess-h-whitespace"
  | "hyg.tab-in-body"
  | "hyg.control-chars"
  | "hyg.zero-width-misuse"
  | "hyg.empty-verse"
  | "hyg.invalid-codepoint"
  | "hyg.replacement-run"
  | "prop.length-ratio"
  | "struct.source-marker-leftover"
  | "struct.merge-conflict-marker"
  | "punct.adjacency-anomaly"
  | "lex.duplicate-word"
  | "lex.punct-only-token"
  | "uni.combining-mark-without-base"
  | "uni.redundant-zero-width-space"
  | "uni.mixed-script-in-token"
  | "lex.repeated-character-run"
  | "uni.mixed-numeral-systems"
  | "punct.bracket-balance"
  | "punct.spacing-anomaly"
  | "case.sentence-initial-lowercase"
  | "case.inconsistent-word-casing"
  | "uni.rare-glyph"
  | "case.mixed-case-word"
  | "uni.mixed-normalization"
  | "lex.untranslated-word";

export type Severity = "error" | "warning" | "info";

export type InputDependency =
  | "target-only"
  | "target-and-reference-silent-when-absent";

export type DigestShape = "none" | "count-pair" | "u32";

/** The 4-byte per-code payload, interpreted by the record's rule. */
export type Digest =
  | { shape: "none" }
  | { shape: "count-pair"; a: number; b: number; saturated: boolean }
  | { shape: "u32"; value: number };

export interface SchemaRule {
  code: number;
  rule_id: WireRuleId;
  digest: DigestShape;
  input_dependency: InputDependency;
}

export interface WireSchema {
  magic: string;
  version: number;
  record_len: number;
  header_len: number;
  offsets: Record<string, number>;
  flag_bits: Record<string, number>;
  severities: Array<[number, Severity]>;
  rules: SchemaRule[];
}

export declare const WIRE_SCHEMA: WireSchema;
export declare const HEADER: {
  MAGIC: string;
  VERSION: number;
  RECORD_LEN: number;
  HEADER_LEN: number;
  OFFSETS: Record<string, number>;
  FLAGS: Record<string, number>;
};
export declare const SEVERITIES: readonly Severity[];
export declare const CODE_TO_RULE: Readonly<Record<number, WireRuleId>>;
export declare const RULE_TO_CODE: Readonly<Record<WireRuleId, number>>;
export declare const CODE_TO_DIGEST: Readonly<Record<number, DigestShape>>;
export declare const CODE_TO_INPUT_DEPENDENCY: Readonly<Record<number, InputDependency>>;
