//! THROWAWAY prototype — NOT part of the crate's shipped surface.
//!
//! Follow-up to `word_break_survey.rs` / `documentation/calibration/
//! 2026-07-17-word-break-fast-path-survey.md`. That survey argued a
//! word-break fast path could reuse existing `Class` bits plus direct char/
//! range matching for the small enumerable categories, mirroring
//! `crate::grapheme`'s hand-rolled fast path + `COMPLEX` fallback (ADR 0021).
//! This program actually BUILDS that walker (minimal, correctness-only, no
//! performance tuning) and runs it against:
//!
//!   1. The official UCD `WordBreakTest.txt` conformance suite (same ÷/×
//!      format `grapheme.rs`'s `conforms_to_graphemebreaktest` parses).
//!   2. A real-corpus differential against `unicode-segmentation`'s own
//!      `unicode_word_indices()` (WA-subset or the full 1,504-corpus fleet).
//!
//! ## Two promoted bits (Part 2 of the follow-up — now real production code)
//!
//! The first version of this prototype approximated every category via
//! either an existing `Class` bit or a `WordBreakProperty.txt` runtime
//! lookup. Two of those lookups have since been promoted into real `Class`
//! bits (`crates/core/src/charclass.rs`, generated by
//! `xtask/src/gen_charclass_table.rs` from the same UCD ranges) — the last 2
//! genuinely free bits (30, 31; bit 6 stays reserved for a future `clinging`
//! flag), both spent here per the steer to use a free bit when a real case
//! justifies it:
//!
//!   - **`WB_EXTEND`** = `Word_Break` ∈ {Extend, ZWJ}. Deliberately narrower
//!     than `Class::is_extender()` (GCB Extend|SpacingMark|ZWJ, correct for
//!     grapheme clustering, where all three glue to the base) — some
//!     `GCB=SpacingMark` scalars are genuinely `Word_Break=Other` (e.g.
//!     U+0EB3 LAO VOWEL SIGN AM), so `is_extender()` wrongly absorbed them
//!     into the preceding word ("ນ້ຳ" (water) split into two word-break
//!     segments per real UAX #29, but `is_extender()`-based absorption fused
//!     it into one — the bug that drove the ~2.07% pre-fix corpus mismatch
//!     rate; see `build_atoms`'s doc comment).
//!   - **`WB_SEP`** = `Word_Break` ∈ {MidLetter, MidNum, MidNumLet,
//!     ExtendNumLet, Single_Quote, Double_Quote} (42 codepoints total) — a
//!     hot-loop candidate-separator fast-reject; `wb_sep_category` below
//!     does the literal char match to disambiguate which of the six on the
//!     rare hit, mirroring how `QUOTE_CHARS` is hardcoded rather than looked
//!     up from a UCD file at runtime.
//!
//! `Format` (58 UCD codepoints) wasn't promoted — still a
//! `WordBreakProperty.txt` lookup, same as `Hebrew_Letter`/`Katakana`/
//! `WSegSpace`/the `ALetter`/`Numeric` residual patches below (none of those
//! were in scope for the bit promotion).
//!
//! ## Design (mirrors `grapheme.rs`'s fast-path/COMPLEX-fallback shape)
//!
//! Any scalar with `Class::is_complex()` set (Hangul jamo pieces, Regional
//! Indicator, Extended_Pictographic/emoji, Prepend, Control, CR, LF — the
//! exact same bit `grapheme.rs` uses to punt to `unicode-segmentation`)
//! defers the WHOLE input string to the crate's own `split_word_bounds`/
//! `unicode_word_indices`. Scripture has ~zero emoji/flags/Hangul (per
//! `grapheme.rs`'s own module doc), so this fallback should be rare, not
//! load-bearing — exactly like the grapheme segmenter's `COMPLEX` bucket.
//!
//! For everything else, this hand-rolls a subset of UAX #29 (WB3d-WB13b;
//! WB1/2/3/3a/3b/3c/15/16 are subsumed by the `is_complex` fallback since
//! CR/LF/Newline/Regional_Indicator/Extended_Pictographic are all
//! `is_complex()==true` — verified directly against `GraphemeBreakProperty.txt`
//! before writing this):
//!
//!   - `ALetter`  ≈ `class_of(c).is_alphabetic()` MINUS scripts the survey
//!     found diverge (Thai/Lao/Khmer/Myanmar/Han/Hiragana — scriptio
//!     continua scripts UAX #29 deliberately excludes from `ALetter`), PLUS
//!     a tiny exact-match patch for the residual the corpus differential
//!     found (`wb == Wb::ALetter`; e.g. U+00B8 CEDILLA, GC=Sk not alphabetic
//!     but genuinely `Word_Break=ALetter`).
//!   - `Numeric`  ≈ `class_of(c).is_decimal_digit()` PLUS the same kind of
//!     exact-match patch (`wb == Wb::Numeric`; e.g. U+066B ARABIC DECIMAL
//!     SEPARATOR, GC=Po not a digit but genuinely `Word_Break=Numeric`).
//!   - `Extend`/`ZWJ` (the bulk of the WB4 "ignore" set) ← `Class::is_wb_extend()`
//!     (the promoted bit); `Format` stays a small `wb == Wb::Format` lookup.
//!   - `MidLetter`/`MidNum`/`MidNumLet`/`ExtendNumLet`/`Single_Quote`/
//!     `Double_Quote` ← `Class::is_wb_sep()` (the promoted bit) plus
//!     `wb_sep_category`'s literal match.
//!   - `Hebrew_Letter`, `Katakana`, `WSegSpace` — still parsed directly from
//!     the committed `WordBreakProperty.txt` (small enumerable categories
//!     out of scope for the bit promotion; exact UCD lookup costs nothing
//!     for them either).
//!
//! Run: cargo run -p ssc-core --release --example word_break_prototype

use std::hint::black_box;
use std::path::Path;
use std::time::Instant;

use unicode_segmentation::UnicodeSegmentation;

use ssc_core::charclass::{Class, class_of};
use ssc_core::corpus::by_book;

#[path = "../dev/vref_io.rs"]
mod vref_io;
use vref_io::corpus_path;

// ---------------------------------------------------------------------
// UCD Word_Break parsing (same shape as word_break_survey.rs — duplicated,
// not shared, since both are independent throwaway examples).
// ---------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Wb {
    ALetter,
    CR,
    DoubleQuote,
    Extend,
    ExtendNumLet,
    Format,
    HebrewLetter,
    Katakana,
    LF,
    MidLetter,
    MidNum,
    MidNumLet,
    Newline,
    Numeric,
    RegionalIndicator,
    SingleQuote,
    WSegSpace,
    ZWJ,
    Other,
}

fn parse_word_break(path: &Path) -> Vec<(u32, u32, Wb)> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let mut parts = line.split(';');
        let cps = parts.next().unwrap().trim();
        let prop = parts.next().unwrap_or("").trim();
        let wb = match prop {
            "ALetter" => Wb::ALetter,
            "CR" => Wb::CR,
            "Double_Quote" => Wb::DoubleQuote,
            "Extend" => Wb::Extend,
            "ExtendNumLet" => Wb::ExtendNumLet,
            "Format" => Wb::Format,
            "Hebrew_Letter" => Wb::HebrewLetter,
            "Katakana" => Wb::Katakana,
            "LF" => Wb::LF,
            "MidLetter" => Wb::MidLetter,
            "MidNum" => Wb::MidNum,
            "MidNumLet" => Wb::MidNumLet,
            "Newline" => Wb::Newline,
            "Numeric" => Wb::Numeric,
            "Regional_Indicator" => Wb::RegionalIndicator,
            "Single_Quote" => Wb::SingleQuote,
            "WSegSpace" => Wb::WSegSpace,
            "ZWJ" => Wb::ZWJ,
            other => panic!("unexpected Word_Break value {other:?}"),
        };
        let (lo, hi) = match cps.split_once("..") {
            Some((a, b)) => (
                u32::from_str_radix(a.trim(), 16).unwrap(),
                u32::from_str_radix(b.trim(), 16).unwrap(),
            ),
            None => {
                let v = u32::from_str_radix(cps, 16).unwrap();
                (v, v)
            }
        };
        out.push((lo, hi, wb));
    }
    out.sort_unstable_by_key(|&(lo, ..)| lo);
    out
}

#[inline]
fn wb_of(ranges: &[(u32, u32, Wb)], c: char) -> Wb {
    let cp = c as u32;
    match ranges.binary_search_by(|&(lo, hi, _)| {
        if cp < lo {
            std::cmp::Ordering::Greater
        } else if cp > hi {
            std::cmp::Ordering::Less
        } else {
            std::cmp::Ordering::Equal
        }
    }) {
        Ok(i) => ranges[i].2,
        Err(_) => Wb::Other,
    }
}

// ---------------------------------------------------------------------
// The prototype walker itself.
// ---------------------------------------------------------------------

/// The atom categories the boundary rules below actually distinguish. Coarser
/// than `Wb` — `RegionalIndicator`/`CR`/`LF`/`Newline`/`Extend`/`Format`/`ZWJ`
/// never reach this type (handled by the `is_complex` bail or WB4 absorption
/// before classification).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum WCat {
    ALetter,
    HebrewLetter,
    Katakana,
    Numeric,
    ExtendNumLet,
    MidLetter,
    MidNum,
    MidNumLet,
    SingleQuote,
    DoubleQuote,
    WSegSpace,
    Other,
}

/// Scripts the survey found genuinely diverge from `is_alphabetic()` for
/// `ALetter` purposes (scriptio continua scripts UAX #29 routes to
/// `Word_Break=Other`, per direct inspection of `WordBreakProperty.txt`).
/// `Kana`/`Hebr` are included defensively even though those scalars are
/// already routed to their own `WCat` variant before this check runs.
const ALETTER_EXCLUDED_SCRIPTS: [&str; 8] =
    ["Thai", "Laoo", "Khmr", "Mymr", "Hani", "Hira", "Kana", "Hebr"];

/// Disambiguates which of the 6 `WB_SEP`-bit categories a scalar belongs to
/// — only called once `Class::is_wb_sep()` has already fast-rejected
/// everything else, so this never runs on the hot path for ALetter/Numeric/
/// Other-bearing text. Hardcoded from the exact `WordBreakProperty.txt`
/// ranges (42 codepoints total across all six categories, confirmed against
/// the committed file), mirroring how `charclass_table.rs`'s `QUOTE_CHARS`
/// is a literal, not a runtime UCD lookup.
fn wb_sep_category(c: char) -> WCat {
    match c as u32 {
        0x0022 => WCat::DoubleQuote,
        0x0027 => WCat::SingleQuote,
        0x003A | 0x00B7 | 0x0387 | 0x055F | 0x05F4 | 0x2027 | 0xFE13 | 0xFE55 | 0xFF1A => {
            WCat::MidLetter
        }
        0x002C | 0x003B | 0x037E | 0x0589 | 0x060C | 0x060D | 0x066C | 0x07F8 | 0x2044
        | 0xFE50 | 0xFE54 | 0xFF0C | 0xFF1B => WCat::MidNum,
        0x002E | 0x2018 | 0x2019 | 0x2024 | 0xFE52 | 0xFF07 | 0xFF0E => WCat::MidNumLet,
        0x005F | 0x202F | 0x203F | 0x2040 | 0x2054 | 0xFE33 | 0xFE34 | 0xFE4D | 0xFE4E
        | 0xFE4F | 0xFF3F => WCat::ExtendNumLet,
        other => unreachable!(
            "Class::is_wb_sep() set for U+{other:04X} but it isn't in the \
             42-codepoint WB_SEP set — charclass_table.rs and this match drifted"
        ),
    }
}

/// The 14 `Word_Break=WSegSpace` codepoints, hardcoded (same reasoning as
/// `wb_sep_category` — small enough to enumerate, not worth a `wb_of()`
/// binary search on the common per-space-character path).
#[inline]
fn is_wb_wsegspace(c: char) -> bool {
    matches!(
        c as u32,
        0x0020 | 0x1680 | 0x2000..=0x2006 | 0x2008..=0x200A | 0x205F | 0x3000
    )
}

/// The 58 `Word_Break=Format` codepoints, hardcoded for the same reason —
/// this is on the WB4-absorption hot path (every scalar), so it must not be
/// a `wb_of()` binary search.
#[inline]
fn is_wb_format(c: char) -> bool {
    matches!(
        c as u32,
        0x00AD
            | 0x061C
            | 0x180E
            | 0x200E..=0x200F
            | 0x202A..=0x202E
            | 0x2060..=0x2064
            | 0x2066..=0x206F
            | 0xFEFF
            | 0xFFF9..=0xFFFB
            | 0x13430..=0x1343F
            | 0x1BCA0..=0x1BCA3
            | 0x1D173..=0x1D17A
            | 0xE0001
    )
}

/// The 75 `Word_Break=Hebrew_Letter` codepoints, hardcoded. Checked BEFORE
/// the `is_alphabetic()` fast path below, not after — unlike the genuinely
/// rare fallthrough categories. Almost every Hebrew letter (and Katakana
/// scalar, below) IS `is_alphabetic()==true`, so checking alphabetic-ness
/// first would misclassify them as plain `ALetter` before this ever ran.
/// This is not hypothetical: the first attempt at reordering `classify` for
/// speed did exactly that, and the full-fleet conformance re-run caught it
/// immediately (U+3031 VERTICAL KANA REPEAT MARK, GC=Lm, `is_alphabetic()`
/// true, wrongly landed as `ALetter` instead of `Katakana` — 28 conformance
/// failures and 167 real `jpn1965`/Hebrew-corpus mismatches before this fix).
#[inline]
fn is_wb_hebrew_letter(cp: u32) -> bool {
    matches!(
        cp,
        0x05D0..=0x05EA
            | 0x05EF..=0x05F2
            | 0xFB1D
            | 0xFB1F..=0xFB28
            | 0xFB2A..=0xFB36
            | 0xFB38..=0xFB3C
            | 0xFB3E
            | 0xFB40..=0xFB41
            | 0xFB43..=0xFB44
            | 0xFB46..=0xFB4F
    )
}

/// The 331 `Word_Break=Katakana` codepoints, hardcoded — same reasoning and
/// same ordering requirement as `is_wb_hebrew_letter` above.
#[inline]
fn is_wb_katakana(cp: u32) -> bool {
    matches!(
        cp,
        0x3031..=0x3035
            | 0x309B..=0x309C
            | 0x30A0
            | 0x30A1..=0x30FA
            | 0x30FC..=0x30FE
            | 0x30FF
            | 0x31F0..=0x31FF
            | 0x32D0..=0x32FE
            | 0x3300..=0x3357
            | 0xFF66..=0xFF6F
            | 0xFF70
            | 0xFF71..=0xFF9D
            | 0x1AFF0..=0x1AFF3
            | 0x1AFF5..=0x1AFFB
            | 0x1AFFD..=0x1AFFE
            | 0x1B000
            | 0x1B120..=0x1B122
            | 0x1B155
            | 0x1B164..=0x1B167
    )
}

/// Classify a non-absorbed, non-`is_complex` scalar. Ordered cheapest-first
/// — `wb_of()` (an O(log 1432) binary search over the parsed
/// `WordBreakProperty.txt` ranges) is called ONLY in the final fallthrough,
/// not per scalar. The first perf-bench run (Part 3) measured the
/// straight-line "compute `wb_of()` unconditionally, then classify" version
/// at 0.11-0.92x on Latin/Ethiopic corpora — SLOWER than
/// `unicode-segmentation`, entirely because of that unconditional binary
/// search. This reordering is what turns "a correct prototype" into
/// something that actually behaves like a fast path. `Hebrew_Letter`/
/// `Katakana` MUST be checked before the `is_alphabetic()` fast path (see
/// their doc comments) — every other cheap check here is order-independent.
fn classify(c: char, cl: Class, wb_ranges: &[(u32, u32, Wb)]) -> WCat {
    if cl.is_wb_sep() {
        // The promoted `WB_SEP` bit (Part 2): fast-reject via one bit test,
        // then a literal char match for the rare hit.
        return wb_sep_category(c);
    }
    if cl.is_decimal_digit() {
        // `is_decimal_digit` (GC=Nd only) is the primary `Numeric` reuse —
        // ~98%+ of real Word_Break=Numeric codepoints per the survey. The
        // small residual (`Wb::Numeric` codepoints that are GC=Po, not Nd —
        // e.g. U+066B ARABIC DECIMAL SEPARATOR) is handled in the
        // fallthrough below, not here, so this branch stays a single bit
        // test.
        return WCat::Numeric;
    }
    let cp = c as u32;
    if is_wb_hebrew_letter(cp) {
        return WCat::HebrewLetter;
    }
    if is_wb_katakana(cp) {
        return WCat::Katakana;
    }
    let excluded_script = cl
        .script()
        .is_some_and(|s| ALETTER_EXCLUDED_SCRIPTS.contains(&s.name()));
    if cl.is_alphabetic() && !excluded_script {
        // `is_alphabetic()` + script exclusion is the primary `ALetter`
        // reuse (99.81% of ALetter globally, per the survey). The small
        // residual (`Wb::ALetter` codepoints that aren't `is_alphabetic()` —
        // e.g. U+00B8 CEDILLA, GC=Sk) is handled in the fallthrough below.
        return WCat::ALetter;
    }
    if is_wb_wsegspace(c) {
        return WCat::WSegSpace;
    }
    // Rare fallthrough: genuine `Other`, or one of the two known small
    // residual patches (`Wb::ALetter`/`Wb::Numeric` codepoints the cheap
    // bit/predicate checks above missed — U+00B8 CEDILLA and U+066B ARABIC
    // DECIMAL SEPARATOR, both found via the corpus differential). This is
    // the ONLY place `wb_of()`'s binary search runs — by construction rare
    // (scripture's "Other" bucket is ~0.2-3.7% of scalars per the survey's
    // frequency tables, plus the vanishingly rare two residual codepoints),
    // not the common per-char path.
    match wb_of(wb_ranges, c) {
        Wb::ALetter => WCat::ALetter,
        Wb::Numeric => WCat::Numeric,
        _ => WCat::Other,
    }
}

/// One atom: byte span, category, and whether any `Extend`/`Format`/`ZWJ`
/// scalar was absorbed into it (WB4). That flag matters for exactly one
/// rule: WB3d (`WSegSpace × WSegSpace`) is written with NO
/// `(Extend|Format|ZWJ)*` transparency, unlike WB5-WB13b — confirmed against
/// `WordBreakTest.txt` line 1206 (`SPACE × Extend ÷ SPACE`, tagged rule
/// `[999.0]`, the catch-all, not `[3.4]`/WB3d): once a `WSegSpace` has
/// absorbed a trailing mark, it no longer joins a following `WSegSpace`.
#[derive(Clone, Copy)]
struct Atom {
    start: u32,
    end: u32,
    cat: WCat,
    extended: bool,
}

/// Build the atom sequence for `text`, applying WB4 (fold `Extend`/`Format`/
/// `ZWJ` into the preceding atom) inline. Returns `None` (defer to the
/// fallback) if any scalar is `Class::is_complex()` (Hangul jamo pieces,
/// Regional Indicator, emoji, Prepend, Control, CR, LF — confirmed by direct
/// inspection of `GraphemeBreakProperty.txt` to cover every WordBreakTest.txt
/// case touching those categories) or if a leading Extend/Format/ZWJ run has
/// no preceding atom to attach to (a genuinely rare edge case — a verse
/// starting with a bare combining mark).
fn build_atoms(text: &str, wb_ranges: &[(u32, u32, Wb)]) -> Option<Vec<Atom>> {
    let mut atoms: Vec<Atom> = Vec::new();
    for (i, c) in text.char_indices() {
        let cl = class_of(c);
        if cl.is_complex() {
            return None;
        }
        // The promoted `WB_EXTEND` bit (Part 2): `Word_Break` in
        // {Extend, ZWJ}, NOT `SpacingMark` — deliberately narrower than
        // `Class::is_extender()` (GCB Extend|SpacingMark|ZWJ), which is
        // correct for grapheme clustering (all three glue to the base) but
        // was wrong here: some `GCB=SpacingMark` scalars are genuinely
        // `Word_Break=Other` (e.g. U+0EB3 LAO VOWEL SIGN AM), so absorbing
        // them via `is_extender()` wrongly fused "ນ້ຳ" (water) into one
        // word-break segment when real UAX #29 splits it into two — the bug
        // that drove the ~2.07% pre-fix corpus mismatch rate (see the
        // markdown report's "prototype conformance" section). `is_wb_format`
        // is a hardcoded 58-codepoint check, not a `wb_of()` binary search —
        // this runs on every scalar, so it must stay cheap.
        let absorbed = cl.is_wb_extend() || is_wb_format(c);
        if absorbed {
            match atoms.last_mut() {
                Some(last) => {
                    last.end = (i + c.len_utf8()) as u32;
                    last.extended = true;
                }
                None => return None,
            }
            continue;
        }
        let cat = classify(c, cl, wb_ranges);
        atoms.push(Atom {
            start: i as u32,
            end: (i + c.len_utf8()) as u32,
            cat,
            extended: false,
        });
    }
    Some(atoms)
}

#[inline]
fn is_ah(c: WCat) -> bool {
    matches!(c, WCat::ALetter | WCat::HebrewLetter)
}
#[inline]
fn is_midnumletq(c: WCat) -> bool {
    matches!(c, WCat::MidNumLet | WCat::SingleQuote)
}

/// `true` if there is NO break between `atoms[i]` and `atoms[i+1]` — i.e. one
/// of WB3d/WB5-WB13b fires. `false` (the WB999 catch-all) otherwise.
fn no_break(atoms: &[Atom], i: usize) -> bool {
    let cur = atoms[i].cat;
    let next = atoms[i + 1].cat;
    let prev = if i > 0 { Some(atoms[i - 1].cat) } else { None };
    let next2 = atoms.get(i + 2).map(|a| a.cat);

    if !atoms[i].extended && cur == WCat::WSegSpace && next == WCat::WSegSpace {
        return true; // WB3d — no (Extend|Format|ZWJ)* transparency on this one
    }
    if is_ah(cur) && is_ah(next) {
        return true; // WB5
    }
    if is_ah(cur) && (next == WCat::MidLetter || is_midnumletq(next)) && next2.is_some_and(is_ah) {
        return true; // WB6
    }
    if (cur == WCat::MidLetter || is_midnumletq(cur)) && is_ah(next) && prev.is_some_and(is_ah) {
        return true; // WB7
    }
    if cur == WCat::HebrewLetter && next == WCat::SingleQuote {
        return true; // WB7a
    }
    if cur == WCat::HebrewLetter && next == WCat::DoubleQuote && next2 == Some(WCat::HebrewLetter)
    {
        return true; // WB7b
    }
    if cur == WCat::DoubleQuote && next == WCat::HebrewLetter && prev == Some(WCat::HebrewLetter) {
        return true; // WB7c
    }
    if cur == WCat::Numeric && next == WCat::Numeric {
        return true; // WB8
    }
    if is_ah(cur) && next == WCat::Numeric {
        return true; // WB9
    }
    if cur == WCat::Numeric && is_ah(next) {
        return true; // WB10
    }
    if (cur == WCat::MidNum || is_midnumletq(cur))
        && next == WCat::Numeric
        && prev == Some(WCat::Numeric)
    {
        return true; // WB11
    }
    if cur == WCat::Numeric
        && (next == WCat::MidNum || is_midnumletq(next))
        && next2 == Some(WCat::Numeric)
    {
        return true; // WB12
    }
    if cur == WCat::Katakana && next == WCat::Katakana {
        return true; // WB13
    }
    if (is_ah(cur) || cur == WCat::Numeric || cur == WCat::Katakana || cur == WCat::ExtendNumLet)
        && next == WCat::ExtendNumLet
    {
        return true; // WB13a
    }
    if cur == WCat::ExtendNumLet && (is_ah(next) || next == WCat::Numeric || next == WCat::Katakana)
    {
        return true; // WB13b
    }
    false // WB999
}

/// Full (unfiltered) UAX #29 boundary offsets for `text` — `Some(list)`
/// starting at 0 and ending at `text.len()` if handled by the hand-rolled
/// path, `None` if deferred to the fallback.
fn word_boundaries(text: &str, wb_ranges: &[(u32, u32, Wb)]) -> Option<Vec<usize>> {
    let atoms = build_atoms(text, wb_ranges)?;
    let mut boundaries = vec![0usize];
    for i in 0..atoms.len().saturating_sub(1) {
        if !no_break(&atoms, i) {
            boundaries.push(atoms[i + 1].start as usize);
        }
    }
    boundaries.push(text.len());
    Some(boundaries)
}

/// The crate's own full (unfiltered) UAX #29 boundaries — the fallback answer
/// and the conformance oracle for deferred cases.
fn oracle_word_boundaries(text: &str) -> Vec<usize> {
    let mut b: Vec<usize> = text.split_word_bound_indices().map(|(i, _)| i).collect();
    b.push(text.len());
    b
}

/// Filters full boundaries down to alphanumeric-bearing segments — the same
/// contract `token.rs`'s `tokenize_into` relies on from `unicode_word_indices`
/// ("a token is a word-boundary segment that contains an alphanumeric
/// character").
fn alnum_tokens(text: &str, boundaries: &[usize]) -> Vec<(usize, usize)> {
    boundaries
        .windows(2)
        .map(|w| (w[0], w[1]))
        .filter(|&(s, e)| {
            text[s..e].chars().any(|c| {
                let cl = class_of(c);
                cl.is_alphabetic() || cl.is_numeric()
            })
        })
        .collect()
}

/// Which path produced `my_tokens`' output for a verse. `AsciiGate` and
/// `ComplexDeferred` both literally call `unicode_word_indices()` themselves,
/// so a "does it match the reference" check on either is trivial by
/// construction — only `HandRolled` is a meaningful correctness test of this
/// prototype's own rule logic.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum TokenPath {
    /// Whole string is ASCII — delegated to `unicode_word_indices()` without
    /// ever running the hand-rolled walker (the follow-up in this section).
    AsciiGate,
    /// The hand-rolled `Class`-bit-driven walker produced the tokens.
    HandRolled,
    /// `Class::is_complex()` (or a leading-extend edge case) forced a defer.
    ComplexDeferred,
}

/// My tokens for `text` — `(tokens, path)`. Mirrors `unicode-segmentation`'s
/// own whole-string ASCII gate (`word.rs` ~973-976) FIRST: `str::is_ascii()`
/// is a cheap, already-word-chunked std check (no need to hand-roll anything
/// faster — SIMD was considered and ruled out here as not worth it). On
/// ASCII input the crate is already at its own fast-path floor (~495ns/verse
/// on English, per the Part 3 bench below) — there's nothing to beat, only
/// to match, and delegating means zero new correctness surface on that
/// branch (no hand-rolled ASCII boundary logic to get subtly wrong, unlike
/// the WB3d/SpacingMark/Hebrew-Katakana bugs already found and fixed on the
/// non-ASCII path). The hand-rolled walker only ever runs on `!is_ascii()`
/// text, where it has already shown a real, measured win.
fn my_tokens(text: &str, wb_ranges: &[(u32, u32, Wb)]) -> (Vec<(usize, usize)>, TokenPath) {
    if text.is_ascii() {
        return (
            text.unicode_word_indices()
                .map(|(s, w)| (s, s + w.len()))
                .collect(),
            TokenPath::AsciiGate,
        );
    }
    match word_boundaries(text, wb_ranges) {
        Some(b) => (alnum_tokens(text, &b), TokenPath::HandRolled),
        None => (
            text.unicode_word_indices()
                .map(|(s, w)| (s, s + w.len()))
                .collect(),
            TokenPath::ComplexDeferred,
        ),
    }
}

/// `my_tokens` with the ASCII gate forced off — always runs the hand-rolled
/// walker, even on pure-ASCII text. Bench-only: isolates the gate's own
/// contribution to the Part-3 throughput numbers from the separate
/// materialization-fairness fix (see `run_perf_bench`'s doc comment), by
/// reproducing exactly what `my_tokens` did before this follow-up, measured
/// with the same (corrected) methodology as everything else.
fn my_tokens_no_ascii_gate(text: &str, wb_ranges: &[(u32, u32, Wb)]) -> Vec<(usize, usize)> {
    match word_boundaries(text, wb_ranges) {
        Some(b) => alnum_tokens(text, &b),
        None => text
            .unicode_word_indices()
            .map(|(s, w)| (s, s + w.len()))
            .collect(),
    }
}

// ---------------------------------------------------------------------
// Coordinator follow-up: the N=5 per-book adaptive gate. Sample the first
// `ADAPTIVE_SAMPLE_N` verses of a BOOK (not verse-by-verse), decide ONCE
// whether to delegate the whole book to `unicode_word_indices()` or run the
// hand-rolled walker for the whole book, then apply that single decision to
// every verse without re-checking `is_ascii()` per verse at all — a plain
// local decision variable, no atomic/mutex (see the per-book design note:
// each book's own walk is already sequential, even under the parallel
// per-book fan-out, so there's nothing to synchronize).
// ---------------------------------------------------------------------

const ADAPTIVE_SAMPLE_N: usize = 5;
/// PLACEHOLDER, not a measured crossover. The per-book sampling section
/// above only pins down ~0% (crate wins big), ~10% (crate still wins), and
/// ~50%+ (hand-rolled walker wins big) — the real threshold between "commit
/// to delegating" and "commit to the walker" is unmeasured. 30% is simply
/// the midpoint of the still-unmeasured 10-50% gap, chosen so this strategy
/// can be measured at all. Treat every number produced with this constant
/// as provisional pending the real crossover measurement.
const ADAPTIVE_THRESHOLD: f64 = 0.30;

/// Tokenizes every verse of one book under the N=5 adaptive strategy,
/// returning the total token count (materializing each verse's `Vec` the
/// same way `my_tokens` does, summed rather than collected, since the bench
/// only needs the count to force materialization and prevent the optimizer
/// from eliding the work).
fn book_tokens_adaptive(texts: &[String], wb_ranges: &[(u32, u32, Wb)]) -> usize {
    let sample_n = ADAPTIVE_SAMPLE_N.min(texts.len());
    let (mut na, mut tot) = (0u64, 0u64);
    for t in &texts[..sample_n] {
        for c in t.chars() {
            tot += 1;
            if !c.is_ascii() {
                na += 1;
            }
        }
    }
    let density = if tot > 0 { na as f64 / tot as f64 } else { 0.0 };
    let delegate = density < ADAPTIVE_THRESHOLD;

    let mut total_tokens = 0usize;
    for t in texts {
        let toks: Vec<(usize, usize)> = if delegate {
            t.unicode_word_indices()
                .map(|(s, w)| (s, s + w.len()))
                .collect()
        } else {
            match word_boundaries(t, wb_ranges) {
                Some(b) => alnum_tokens(t, &b),
                None => t
                    .unicode_word_indices()
                    .map(|(s, w)| (s, s + w.len()))
                    .collect(),
            }
        };
        total_tokens += toks.len();
    }
    total_tokens
}

// ---------------------------------------------------------------------
// 1. Conformance: run every WordBreakTest.txt case.
// ---------------------------------------------------------------------

fn run_conformance(wb_ranges: &[(u32, u32, Wb)]) {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let data = std::fs::read_to_string(manifest_dir.join("src/testdata/ucd/WordBreakTest.txt"))
        .expect("read WordBreakTest.txt");

    let (mut handled_pass, mut handled_fail) = (0u32, 0u32);
    let (mut deferred_pass, mut deferred_fail) = (0u32, 0u32);
    let mut failures: Vec<(String, Vec<usize>, Vec<usize>)> = Vec::new();

    for line in data.lines() {
        let line = line.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let mut s = String::new();
        let mut expected = Vec::new();
        for tok in line.split_whitespace() {
            match tok {
                "÷" => expected.push(s.len()),
                "×" => {}
                hex => {
                    let c = char::from_u32(u32::from_str_radix(hex, 16).unwrap()).unwrap();
                    s.push(c);
                }
            }
        }

        match word_boundaries(&s, wb_ranges) {
            Some(actual) => {
                if actual == expected {
                    handled_pass += 1;
                } else {
                    handled_fail += 1;
                    if failures.len() < 8 {
                        failures.push((s.clone(), expected.clone(), actual));
                    }
                }
            }
            None => {
                // Deferred: sanity-check the fallback itself agrees with the
                // UCD suite (should always hold — it's the reference impl).
                let oracle = oracle_word_boundaries(&s);
                if oracle == expected {
                    deferred_pass += 1;
                } else {
                    deferred_fail += 1;
                }
            }
        }
    }

    let total = handled_pass + handled_fail + deferred_pass + deferred_fail;
    println!("=== WordBreakTest.txt conformance ===");
    println!("total cases: {total}");
    println!(
        "handled by hand-rolled path: {} pass, {} fail",
        handled_pass, handled_fail
    );
    println!(
        "deferred to fallback (trivial, sanity-check only): {} pass, {} fail",
        deferred_pass, deferred_fail
    );
    if !failures.is_empty() {
        println!("\n--- first {} hand-rolled failures ---", failures.len());
        for (s, expected, actual) in &failures {
            let hex: Vec<String> = s.chars().map(|c| format!("U+{:04X}", c as u32)).collect();
            println!("input: {} ({s:?})", hex.join(" "));
            println!("  expected boundaries: {expected:?}");
            println!("  actual   boundaries: {actual:?}");
        }
    }
}

// ---------------------------------------------------------------------
// 2. Real-corpus differential vs unicode-segmentation.
// ---------------------------------------------------------------------

fn run_corpus_differential(wb_ranges: &[(u32, u32, Wb)], scope: &str) {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let corpora_dir = manifest_dir.join("../../corpora/vref");
    let mut wa_files: Vec<std::path::PathBuf> = std::fs::read_dir(&corpora_dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", corpora_dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
            name.ends_with(".txt") && (scope == "full" || name.starts_with("WA-"))
        })
        .collect();
    wa_files.sort();

    let mut total_verses = 0u64;
    let mut ascii_gate_verses = 0u64;
    let mut hand_rolled_verses = 0u64;
    let mut complex_deferred_verses = 0u64;
    let mut hand_rolled_match = 0u64;
    let mut hand_rolled_mismatch = 0u64;
    let mut trivial_match = 0u64;
    let mut trivial_mismatch = 0u64; // ascii-gate + complex-deferred combined; should stay 0
    let mut mismatch_examples: Vec<(String, String, String, Vec<(usize, usize)>, Vec<(usize, usize)>)> =
        Vec::new();

    for path in &wa_files {
        let id = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default()
            .to_string();
        let corpus = vref_io::load_corpus(path);
        for (key, text) in corpus.keys().iter().zip(corpus.texts()) {
            total_verses += 1;
            let (mine, path_taken) = my_tokens(text, wb_ranges);
            let real: Vec<(usize, usize)> = text
                .unicode_word_indices()
                .map(|(s, w)| (s, s + w.len()))
                .collect();
            let matches = mine == real;
            match path_taken {
                TokenPath::AsciiGate => {
                    ascii_gate_verses += 1;
                    if matches {
                        trivial_match += 1;
                    } else {
                        trivial_mismatch += 1;
                    }
                }
                TokenPath::ComplexDeferred => {
                    complex_deferred_verses += 1;
                    if matches {
                        trivial_match += 1;
                    } else {
                        trivial_mismatch += 1;
                    }
                }
                TokenPath::HandRolled => {
                    hand_rolled_verses += 1;
                    if matches {
                        hand_rolled_match += 1;
                    } else {
                        hand_rolled_mismatch += 1;
                        if mismatch_examples.len() < 20 {
                            mismatch_examples.push((
                                id.clone(),
                                key.clone(),
                                text.clone(),
                                mine.clone(),
                                real,
                            ));
                        }
                    }
                }
            }
        }
    }

    println!(
        "\n=== Real-corpus differential (scope={scope}, {} corpora) ===",
        wa_files.len()
    );
    println!("total verses: {total_verses}");
    println!(
        "ASCII-gate delegated (whole string is_ascii(), calls unicode_word_indices() directly): {ascii_gate_verses} ({:.3}%)",
        100.0 * ascii_gate_verses as f64 / total_verses as f64
    );
    println!(
        "handled by hand-rolled path: {hand_rolled_verses} ({:.3}%)",
        100.0 * hand_rolled_verses as f64 / total_verses as f64
    );
    println!(
        "deferred to fallback (is_complex or leading-extend edge case): {complex_deferred_verses} ({:.3}%)",
        100.0 * complex_deferred_verses as f64 / total_verses as f64
    );
    println!(
        "of hand-rolled verses: {hand_rolled_match} match unicode-segmentation exactly, {hand_rolled_mismatch} mismatch ({:.6}% mismatch rate)",
        100.0 * hand_rolled_mismatch as f64 / hand_rolled_verses.max(1) as f64
    );
    println!(
        "of ASCII-gate + complex-deferred (trivial by construction): {trivial_match} match, {trivial_mismatch} mismatch"
    );
    if !mismatch_examples.is_empty() {
        println!("\n--- first {} mismatches ---", mismatch_examples.len());
        for (corpus, key, text, mine, real) in &mismatch_examples {
            println!("{corpus} {key}: {text:?}");
            println!("  mine: {mine:?}");
            println!("  real: {real:?}");
        }
    }
}

// ---------------------------------------------------------------------
// Part 3: throughput — hand-rolled walker vs unicode-segmentation,
// tokenizing-only (materializing tokens), mirroring exactly how ADR 0021
// measured the grapheme segmenter's own speed claim ("2.7-4.9x the oracle
// walk ... segmentation only, incl. materializing spans"). Correctness is
// already established fleet-wide (Parts 1/2 above), so this runs on the
// WA-251 subset only — same bench scope ADR 0021 itself used.
// ---------------------------------------------------------------------

/// One corpus per script, picked from what's actually present in the WA-251
/// sample (checked via `ls corpora/vref | grep WA-`) — not the exact ADR
/// 0021 script list (this repo's WA subset has no Cyrillic or CJK/Japanese
/// corpus), but comparable breadth: 3 Latin-script languages plus 6 distinct
/// non-Latin scripts.
const BENCH_CORPORA: &[(&str, &str)] = &[
    ("WA-en-ulb", "Latin (English)"),
    ("WA-es-419-ulb", "Latin (Spanish)"),
    ("WA-pt-br-ulb", "Latin (Portuguese)"),
    ("WA-am-ulb", "Ethiopic (Amharic)"),
    ("WA-hi-ulb", "Devanagari (Hindi)"),
    ("WA-ta-ulb", "Tamil"),
    ("WA-ml-ulb", "Malayalam"),
    ("WA-th-ulb", "Thai"),
    ("WA-my-ulb", "Myanmar"),
    ("WA-km-ulb", "Khmer"),
];

/// Median of `trials` full-corpus passes (ns/verse), each preceded by
/// `warmup` untimed passes. `black_box` on the input and the per-call result
/// (same pattern as `word_break_ascii_gate_bench.rs`) prevents the optimizer
/// from hoisting the loop-invariant call.
fn median_ns_per_verse(texts: &[&str], trials: u32, warmup: u32, mut f: impl FnMut(&str) -> usize) -> f64 {
    for _ in 0..warmup {
        for &t in texts {
            black_box(f(black_box(t)));
        }
    }
    let mut times: Vec<f64> = Vec::with_capacity(trials as usize);
    for _ in 0..trials {
        let t0 = Instant::now();
        for &t in texts {
            black_box(f(black_box(t)));
        }
        times.push(t0.elapsed().as_nanos() as f64 / texts.len() as f64);
    }
    times.sort_by(|a, b| a.partial_cmp(b).unwrap());
    times[times.len() / 2]
}

fn run_perf_bench(wb_ranges: &[(u32, u32, Wb)]) {
    const TRIALS: u32 = 7;
    const WARMUP: u32 = 2;

    println!("\n=== Part 3: throughput, hand-rolled walker vs unicode-segmentation (tokenizing-only) ===");
    println!(
        "{:<22} {:<24} {:>8} {:>12} {:>12} {:>8} {:>9} {:>11} {:>9}",
        "corpus", "script", "verses", "mine_ns/v", "oracle_ns/v", "ratio", "ascii_gate%",
        "hand_rolled%", "deferred%"
    );
    for &(id, script) in BENCH_CORPORA {
        let path = corpus_path(id);
        if !path.exists() {
            eprintln!("skip {id}: not present under corpora/vref");
            continue;
        }
        let corpus = vref_io::load_corpus(&path);
        let texts: Vec<&str> = corpus.texts().iter().map(String::as_str).collect();

        let (mut ascii_gate, mut hand_rolled, mut complex_deferred) = (0usize, 0usize, 0usize);
        for &t in &texts {
            match my_tokens(t, wb_ranges).1 {
                TokenPath::AsciiGate => ascii_gate += 1,
                TokenPath::HandRolled => hand_rolled += 1,
                TokenPath::ComplexDeferred => complex_deferred += 1,
            }
        }

        // Both sides materialize a `Vec<(usize, usize)>` of token spans —
        // matching ADR 0021's own framing ("segmentation only, incl.
        // materializing spans"). An earlier version of this bench had
        // `oracle_ns` call `.count()` (no allocation) against `mine_ns`'s
        // `Vec` via `my_tokens` (allocates) — an apples-to-oranges
        // comparison that would have overstated the reference's speed on
        // every corpus. Fixed before trusting any "gap closed" reading.
        let mine_ns = median_ns_per_verse(&texts, TRIALS, WARMUP, |t| {
            my_tokens(t, wb_ranges).0.len()
        });
        let oracle_ns = median_ns_per_verse(&texts, TRIALS, WARMUP, |t| {
            t.unicode_word_indices()
                .map(|(s, w)| (s, s + w.len()))
                .collect::<Vec<_>>()
                .len()
        });

        println!(
            "{:<22} {:<24} {:>8} {:>12.1} {:>12.1} {:>7.2}x {:>10.2}% {:>10.2}% {:>8.2}%",
            id,
            script,
            texts.len(),
            mine_ns,
            oracle_ns,
            oracle_ns / mine_ns,
            100.0 * ascii_gate as f64 / texts.len() as f64,
            100.0 * hand_rolled as f64 / texts.len() as f64,
            100.0 * complex_deferred as f64 / texts.len() as f64
        );
    }

    // Isolate the ASCII gate's own contribution from the materialization-
    // fairness fix above: re-measure the 3 Latin corpora with the gate
    // forced OFF (`my_tokens_no_ascii_gate` — always the hand-rolled walker,
    // reproducing exactly what this bench measured before this follow-up),
    // under the SAME corrected (both-sides-materialize) methodology. This
    // is what separates "the gate helped" from "the fairness fix helped".
    println!("\n--- ASCII gate isolated (Latin corpora only; no-gate vs with-gate, same fair methodology) ---");
    println!(
        "{:<22} {:>12} {:>12} {:>12} {:>9} {:>9}",
        "corpus", "no_gate_ns/v", "with_gate_ns/v", "oracle_ns/v", "no_gate_x", "with_gate_x"
    );
    for &(id, _script) in &BENCH_CORPORA[..3] {
        let path = corpus_path(id);
        if !path.exists() {
            continue;
        }
        let corpus = vref_io::load_corpus(&path);
        let texts: Vec<&str> = corpus.texts().iter().map(String::as_str).collect();

        let no_gate_ns = median_ns_per_verse(&texts, TRIALS, WARMUP, |t| {
            my_tokens_no_ascii_gate(t, wb_ranges).len()
        });
        let with_gate_ns = median_ns_per_verse(&texts, TRIALS, WARMUP, |t| {
            my_tokens(t, wb_ranges).0.len()
        });
        let oracle_ns = median_ns_per_verse(&texts, TRIALS, WARMUP, |t| {
            t.unicode_word_indices()
                .map(|(s, w)| (s, s + w.len()))
                .collect::<Vec<_>>()
                .len()
        });

        println!(
            "{:<22} {:>12.1} {:>12.1} {:>12.1} {:>8.2}x {:>8.2}x",
            id,
            no_gate_ns,
            with_gate_ns,
            oracle_ns,
            oracle_ns / no_gate_ns,
            oracle_ns / with_gate_ns
        );
    }
}

/// Book-scoped timing: same warmup + trial-median pattern as
/// `median_ns_per_verse`, but `f` runs once per BOOK (a `&[String]` of that
/// book's verse texts) instead of once per verse — needed because the N=5
/// adaptive decision is made once per book, not once per verse. `black_box`
/// on the book slice and the per-call result, same as everywhere else in
/// this file.
fn median_ns_per_verse_by_book(
    books: &[ssc_core::corpus::BookGroup<'_>],
    total_verses: usize,
    trials: u32,
    warmup: u32,
    mut f: impl FnMut(&[String]) -> usize,
) -> f64 {
    for _ in 0..warmup {
        for g in books {
            black_box(f(black_box(g.texts)));
        }
    }
    let mut times: Vec<f64> = Vec::with_capacity(trials as usize);
    for _ in 0..trials {
        let t0 = Instant::now();
        for g in books {
            black_box(f(black_box(g.texts)));
        }
        times.push(t0.elapsed().as_nanos() as f64 / total_verses as f64);
    }
    times.sort_by(|a, b| a.partial_cmp(b).unwrap());
    times[times.len() / 2]
}

/// Coordinator follow-up: re-measures Part 3's throughput chart with the
/// N=5 per-book adaptive gate (`book_tokens_adaptive`) in place of the
/// per-verse ASCII gate, same 10 corpora, same fair (both-sides-materialize)
/// methodology as the bugfix above.
fn run_perf_bench_adaptive(wb_ranges: &[(u32, u32, Wb)]) {
    // More trials than the other bench modes: the near-parity corpora here
    // (English, Spanish, Portuguese) run sub-microsecond per verse, which is
    // noise-sensitive enough that a 7-trial median swung 0.55x-0.98x across
    // repeated runs during calibration. 21 trials (taking the median still)
    // was enough to stabilize it.
    const TRIALS: u32 = 21;
    const WARMUP: u32 = 3;

    println!(
        "\n=== N=5 per-book adaptive gate (threshold={:.0}%, PLACEHOLDER — see doc comment) ===",
        ADAPTIVE_THRESHOLD * 100.0
    );
    println!(
        "{:<22} {:<24} {:>8} {:>12} {:>12} {:>8}",
        "corpus", "script", "verses", "mine_ns/v", "oracle_ns/v", "ratio"
    );
    for &(id, script) in BENCH_CORPORA {
        let path = corpus_path(id);
        if !path.exists() {
            eprintln!("skip {id}: not present under corpora/vref");
            continue;
        }
        let corpus = vref_io::load_corpus(&path);
        let books = by_book(&corpus);
        let total_verses: usize = books.iter().map(|g| g.texts.len()).sum();
        let texts: Vec<&str> = corpus.texts().iter().map(String::as_str).collect();

        let mine_ns = median_ns_per_verse_by_book(&books, total_verses, TRIALS, WARMUP, |t| {
            book_tokens_adaptive(t, wb_ranges)
        });
        let oracle_ns = median_ns_per_verse(&texts, TRIALS, WARMUP, |t| {
            t.unicode_word_indices()
                .map(|(s, w)| (s, s + w.len()))
                .collect::<Vec<_>>()
                .len()
        });

        println!(
            "{:<22} {:<24} {:>8} {:>12.1} {:>12.1} {:>7.2}x",
            id,
            script,
            total_verses,
            mine_ns,
            oracle_ns,
            oracle_ns / mine_ns
        );
    }
}

fn main() {
    // Mode/scope selection (mirrors word_break_survey.rs's wa|full
    // convention, plus a `bench` mode for Part 3): `wa` (default,
    // backward-compatible) walks only `WA-*.txt` for the correctness gates;
    // `full` walks every `*.txt` under corpora/vref (the whole 1,504-corpus
    // fleet) for the correctness gates; `bench` skips the correctness gates
    // entirely and runs the Part 3 throughput comparison instead.
    let mode = std::env::args().nth(1).unwrap_or_else(|| "wa".to_string());

    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let wb_ranges = parse_word_break(&manifest_dir.join("src/testdata/ucd/WordBreakProperty.txt"));
    eprintln!("parsed {} Word_Break ranges, mode={mode}", wb_ranges.len());

    if mode == "bench" {
        if corpus_path("WA-en-ulb").exists() {
            run_perf_bench(&wb_ranges);
        } else {
            eprintln!("corpora/vref not present — skipping the throughput bench");
        }
        return;
    }
    if mode == "bench-adaptive" {
        if corpus_path("WA-en-ulb").exists() {
            run_perf_bench_adaptive(&wb_ranges);
        } else {
            eprintln!("corpora/vref not present — skipping the adaptive throughput bench");
        }
        return;
    }

    let scope = if mode == "full" { "full" } else { "wa" };
    run_conformance(&wb_ranges);

    if corpus_path("WA-en-ulb").exists() {
        run_corpus_differential(&wb_ranges, scope);
    } else {
        eprintln!("corpora/vref not present — skipping the real-corpus differential");
    }
}
