// @generated by `cargo xtask wire-js` from ssc-wire's schema. DO NOT EDIT.
// The reviewed decoder/reconciler lives in the hand-written findings.js.

import type {
  WireRuleId,
  Severity,
  InputDependency,
  Digest,
} from "./findings.generated.js";

/** One decoded finding. Addressed by `sid` (the resolved key string), never by
 * the ephemeral wire `key_idx`, so an object survives address rebasing. */
export interface DecodedFinding {
  sid: string;
  code: WireRuleId;
  severity: Severity;
  /** UTF-16 code-unit offset into the verse text. */
  start: number;
  /** UTF-16 code-unit offset (exclusive). */
  end: number;
  score: number | null;
  hasArgs: boolean;
  digest: Digest;
  inputDependency: InputDependency;
}

/** A complete decoded snapshot. `findings[i]` corresponds to wire record `i`
 * under `analysisId` (the snapshot-private lazy-args locator). */
export interface FindingSnapshot {
  analysisId: bigint;
  targetContextId: bigint;
  hasReference: boolean;
  provenance: "live" | "reference-removed";
  findings: DecodedFinding[];
}

export interface ExpectedAnalysisIdentity {
  analysisId: bigint;
  targetContextId: bigint;
  hasReference: boolean;
}

/** Decode a packed buffer, resolving each record's `key_idx` through `keys`.
 * Throws on any malformed/unsupported buffer or out-of-range key index. */
export declare function decodeFindings(
  bytes: Uint8Array,
  keys: string[],
): FindingSnapshot;

/** Fail-closed application-cache decode. Accepts an exact identity triple
 * match, or the single saved-reference-present -> current-reference-absent
 * salvage (matching target-context id) that filters
 * `target-and-reference-silent-when-absent` rows with dense reindexing. */
export declare function decodePersistedFindings(
  bytes: Uint8Array,
  keys: string[],
  expectedIdentity: ExpectedAnalysisIdentity,
): FindingSnapshot;

/** Reconcile a new complete snapshot against a previous one, preserving object
 * identity for visibly-unchanged findings (returns the exact prior array when
 * nothing visible changed). */
export declare function reconcileFindings(
  previousSnapshot: FindingSnapshot,
  bytes: Uint8Array,
  keys: string[],
): FindingSnapshot;
