//! `cargo xtask wire-js` — render the official JS wire surface from `ssc-wire`'s
//! machine-readable schema (granularity-spine Appendix A §A.4).
//!
//! Writes three do-not-edit files into `crates/wasm/js/`:
//! - `findings.generated.js` — the frozen schema object plus derived lookup
//!   tables (constants and code/digest/dependency maps);
//! - `findings.generated.d.ts` — the wire string unions and digest types;
//! - `findings.d.ts` — the public decoder/reconciler API declaration.
//!
//! The reviewed algorithm lives in the hand-written `findings.js`, which imports
//! from `findings.generated.js` and copies no numeric constant or table. Output
//! is deterministic (no timestamps), so running twice is a no-op.

use std::fs;
use std::path::Path;

use ssc_wire::schema::{schema, WireSchema};

const BANNER: &str =
    "// @generated by `cargo xtask wire-js` from ssc-wire's schema. DO NOT EDIT.\n// The reviewed decoder/reconciler lives in the hand-written findings.js.\n";

/// Render and write the three generated files. Returns the number of files whose
/// content changed (0 == the determinism no-op).
pub fn run(wasm_js_dir: &Path) -> usize {
    fs::create_dir_all(wasm_js_dir).expect("create crates/wasm/js");
    let s = schema();

    let files = [
        ("findings.generated.js", render_generated_js(&s)),
        ("findings.generated.d.ts", render_generated_dts(&s)),
        ("findings.d.ts", render_public_dts()),
    ];

    let mut changed = 0;
    for (name, content) in files {
        let path = wasm_js_dir.join(name);
        let existing = fs::read_to_string(&path).ok();
        if existing.as_deref() == Some(content.as_str()) {
            println!("unchanged: {}", path.display());
        } else {
            fs::write(&path, &content).expect("write generated file");
            println!("wrote:     {}", path.display());
            changed += 1;
        }
    }
    changed
}

fn render_generated_js(s: &WireSchema) -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push('\n');

    // The canonical schema object, embedded verbatim (JSON is valid JS).
    out.push_str("export const WIRE_SCHEMA = Object.freeze(\n");
    out.push_str(&ssc_wire::schema::schema_json());
    out.push_str("\n);\n\n");

    // Header constants + offsets + flag bits, from the one schema source.
    let o = &s.offsets;
    let fb = &s.flag_bits;
    out.push_str(&format!(
        "export const HEADER = Object.freeze({{\n  MAGIC: {magic:?},\n  VERSION: {ver},\n  RECORD_LEN: {rlen},\n  HEADER_LEN: {hlen},\n  OFFSETS: Object.freeze({{\n    headerFlags: {hf},\n    count: {cnt},\n    reserved: {res},\n    targetContextId: {tcid},\n    analysisId: {aid},\n    recordCode: {rc},\n    recordFlags: {rf},\n    recordKeyIdx: {rk},\n    recordStart: {rs},\n    recordEnd: {re},\n    recordScore: {rsc},\n    recordPayload: {rp},\n  }}),\n  FLAGS: Object.freeze({{\n    headerHasReference: {hhr},\n    severityMask: {sm},\n    hasScore: {hs},\n    hasArgs: {ha},\n    payloadSaturated: {ps},\n    recordReservedMask: {rrm},\n  }}),\n}});\n\n",
        magic = s.magic,
        ver = s.version,
        rlen = s.record_len,
        hlen = s.header_len,
        hf = o.header_flags,
        cnt = o.header_count,
        res = o.header_reserved,
        tcid = o.header_target_context_id,
        aid = o.header_analysis_id,
        rc = o.record_code,
        rf = o.record_flags,
        rk = o.record_key_idx,
        rs = o.record_start,
        re = o.record_end,
        rsc = o.record_score,
        rp = o.record_payload,
        hhr = fb.header_has_reference,
        sm = fb.record_severity_mask,
        hs = fb.record_has_score,
        ha = fb.record_has_args,
        ps = fb.record_payload_saturated,
        rrm = fb.record_reserved_mask,
    ));

    // Severities (index == numeric encoding).
    let sev = s
        .severities
        .iter()
        .map(|(_, name)| format!("{name:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!("export const SEVERITIES = Object.freeze([{sev}]);\n\n"));

    // Derived lookup tables (all from schema.rules, sorted by code).
    let code_to_rule = s
        .rules
        .iter()
        .map(|r| format!("  \"{}\": {:?},", r.code, r.rule_id))
        .collect::<Vec<_>>()
        .join("\n");
    out.push_str(&format!(
        "export const CODE_TO_RULE = Object.freeze({{\n{code_to_rule}\n}});\n\n"
    ));

    let rule_to_code = s
        .rules
        .iter()
        .map(|r| format!("  {:?}: {},", r.rule_id, r.code))
        .collect::<Vec<_>>()
        .join("\n");
    out.push_str(&format!(
        "export const RULE_TO_CODE = Object.freeze({{\n{rule_to_code}\n}});\n\n"
    ));

    let code_to_digest = s
        .rules
        .iter()
        .map(|r| format!("  \"{}\": {:?},", r.code, r.digest))
        .collect::<Vec<_>>()
        .join("\n");
    out.push_str(&format!(
        "export const CODE_TO_DIGEST = Object.freeze({{\n{code_to_digest}\n}});\n\n"
    ));

    let code_to_dep = s
        .rules
        .iter()
        .map(|r| format!("  \"{}\": {:?},", r.code, r.input_dependency))
        .collect::<Vec<_>>()
        .join("\n");
    out.push_str(&format!(
        "export const CODE_TO_INPUT_DEPENDENCY = Object.freeze({{\n{code_to_dep}\n}});\n"
    ));

    out
}

fn render_generated_dts(s: &WireSchema) -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push('\n');

    let rule_union = s
        .rules
        .iter()
        .map(|r| format!("  | {:?}", r.rule_id))
        .collect::<Vec<_>>()
        .join("\n");
    out.push_str(&format!("export type WireRuleId =\n{rule_union};\n\n"));

    out.push_str("export type Severity = \"error\" | \"warning\" | \"info\";\n\n");
    out.push_str(
        "export type InputDependency =\n  | \"target-only\"\n  | \"target-and-reference-silent-when-absent\";\n\n",
    );
    out.push_str("export type DigestShape = \"none\" | \"count-pair\" | \"u32\";\n\n");
    out.push_str(
        "/** The 4-byte per-code payload, interpreted by the record's rule. */\nexport type Digest =\n  | { shape: \"none\" }\n  | { shape: \"count-pair\"; a: number; b: number; saturated: boolean }\n  | { shape: \"u32\"; value: number };\n\n",
    );

    out.push_str("export interface SchemaRule {\n  code: number;\n  rule_id: WireRuleId;\n  digest: DigestShape;\n  input_dependency: InputDependency;\n}\n\n");
    out.push_str("export interface WireSchema {\n  magic: string;\n  version: number;\n  record_len: number;\n  header_len: number;\n  offsets: Record<string, number>;\n  flag_bits: Record<string, number>;\n  severities: Array<[number, Severity]>;\n  rules: SchemaRule[];\n}\n\n");

    out.push_str("export declare const WIRE_SCHEMA: WireSchema;\n");
    out.push_str("export declare const HEADER: {\n  MAGIC: string;\n  VERSION: number;\n  RECORD_LEN: number;\n  HEADER_LEN: number;\n  OFFSETS: Record<string, number>;\n  FLAGS: Record<string, number>;\n};\n");
    out.push_str("export declare const SEVERITIES: readonly Severity[];\n");
    out.push_str("export declare const CODE_TO_RULE: Readonly<Record<number, WireRuleId>>;\n");
    out.push_str("export declare const RULE_TO_CODE: Readonly<Record<WireRuleId, number>>;\n");
    out.push_str("export declare const CODE_TO_DIGEST: Readonly<Record<number, DigestShape>>;\n");
    out.push_str(
        "export declare const CODE_TO_INPUT_DEPENDENCY: Readonly<Record<number, InputDependency>>;\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn js_dir() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../crates/wasm/js")
    }

    /// Generated-JS conformance (§A.5.6 / §A.6.3): the committed generated files
    /// equal what the current `ssc-wire` schema renders. Together with the
    /// `ssc-wire` discriminant pins, this proves the consumer receives exactly
    /// the schema's mapping — regenerate with `cargo xtask wire-js` if stale.
    #[test]
    fn committed_generated_files_match_render() {
        let s = schema();
        for (name, content) in [
            ("findings.generated.js", render_generated_js(&s)),
            ("findings.generated.d.ts", render_generated_dts(&s)),
            ("findings.d.ts", render_public_dts()),
        ] {
            let committed = fs::read_to_string(js_dir().join(name))
                .unwrap_or_else(|e| panic!("read {name}: {e}"));
            assert_eq!(committed, content, "{name} is stale — run `cargo xtask wire-js`");
        }
    }
}

fn render_public_dts() -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push('\n');
    out.push_str(
        r#"import type {
  WireRuleId,
  Severity,
  InputDependency,
  Digest,
} from "./findings.generated.js";

/**
 * # Findings lifecycle — which decode call, and when
 *
 * SAVE — there is no export method; `galley.analyze()`'s return IS the artifact:
 *
 *     galley.analyze() -> packed bytes (the header already carries the ids)
 *         -> app writes those bytes to its own cache (disk / IndexedDB / OPFS)
 *
 * LOAD — a fresh session, where the cache's provenance must be re-proven:
 *
 *     app loads project text/config
 *         -> new Galley({ target, source?, config })  // validates + hashes; no analysis
 *         -> expected = { analysisId:      galley.expectedAnalysisId(),
 *                         targetContextId: galley.expectedTargetContextId(),
 *                         hasReference:    galley.hasReference() }
 *         -> bytes = app cache read (e.g. "sous-findings.bin")
 *         -> decodePersistedFindings(bytes, target.keys, expected)
 *                ok    -> render immediately (engine-verified exact for current inputs)
 *                throw -> discard the cache entry; continue below
 *         -> fresh = galley.analyze()                  // the cold pass persistence skipped
 *         -> reconcileFindings(persisted, fresh, target.keys) -> render
 *         -> app may overwrite its cache entry with `fresh`
 *
 * LIVE LOOP — same session, buffers minted by the Galley you're holding:
 *
 *     galley.updateBook(...) / updateChapter(...) -> galley.analyze() -> bytes
 *         -> decodeFindings(bytes, keys)               // one-shot / storage-free consumers
 *         -> reconcileFindings(prev, bytes, keys)      // resident UI: unchanged objects reused
 *
 * Rule of thumb: bytes you just watched THIS Galley produce -> `decodeFindings`
 * (provenance is the call itself). Bytes that ever sat in storage ->
 * `decodePersistedFindings` (provenance was laundered away; the identity check
 * restores it). `keys` must always be the exact ordered, duplicate-preserving
 * key array used to construct the Galley that minted/validated the buffer.
 */

/** One decoded finding. Addressed by `sid` (the resolved key string), never by
 * the ephemeral wire `key_idx`, so an object survives address rebasing. */
export interface DecodedFinding {
  sid: string;
  code: WireRuleId;
  severity: Severity;
  /** UTF-16 code-unit offset into the verse text. */
  start: number;
  /** UTF-16 code-unit offset (exclusive). */
  end: number;
  score: number | null;
  hasArgs: boolean;
  digest: Digest;
  inputDependency: InputDependency;
}

/** A complete decoded snapshot. `findings[i]` corresponds to wire record `i`
 * under `analysisId` (the snapshot-private lazy-args locator). */
export interface FindingSnapshot {
  analysisId: bigint;
  targetContextId: bigint;
  hasReference: boolean;
  provenance: "live" | "reference-removed";
  findings: DecodedFinding[];
}

/** The identity a persisted buffer must prove it carries.
 *
 * "Expected" (not "current") because two ids can exist at once: the id of the
 * Galley's *last publication*, and the id *implied by the inputs it holds
 * right now*. They diverge on any mutation, and the second exists even before
 * the first analyze (which is exactly when the load recipe runs). The
 * `expected*` accessors return the second: "any buffer claiming to describe
 * my current inputs must carry this id." The values are engine-minted content
 * hashes (ordered per-book hashes + complete config + engine stamp; the
 * analysis id additionally folds reference presence/content) — the app never
 * computes or interprets them. */
export interface ExpectedAnalysisIdentity {
  analysisId: bigint;
  targetContextId: bigint;
  hasReference: boolean;
}

/** Decode a packed buffer, resolving each record's `key_idx` through `keys`.
 * Throws on any malformed/unsupported buffer or out-of-range key index.
 *
 * Use for bytes whose provenance you hold: the buffer this session's
 * `galley.analyze()` just returned. For bytes read back from storage, use
 * {@link decodePersistedFindings} — shape validation alone cannot prove a
 * stored buffer describes today's text/config/engine. */
export declare function decodeFindings(
  bytes: Uint8Array,
  keys: string[],
): FindingSnapshot;

/** Fail-closed application-cache decode: full wire validation PLUS the
 * identity proof. Accepts an exact identity-triple match, or the single
 * saved-reference-present -> current-reference-absent salvage (matching
 * target-context id) that filters `target-and-reference-silent-when-absent`
 * rows with dense reindexing. Every other mismatch throws.
 *
 * Use for bytes that ever sat in storage. On success the findings are exact —
 * not stale — for the constructing Galley's current inputs, so they may render
 * immediately while the real analyze re-warms in the background (see the
 * module-level lifecycle). Lazy args stay unavailable until that analyze
 * succeeds. */
export declare function decodePersistedFindings(
  bytes: Uint8Array,
  keys: string[],
  expectedIdentity: ExpectedAnalysisIdentity,
): FindingSnapshot;

/** Reconcile a new complete snapshot against a previous one, preserving object
 * identity for visibly-unchanged findings (returns the exact prior array when
 * nothing visible changed). */
export declare function reconcileFindings(
  previousSnapshot: FindingSnapshot,
  bytes: Uint8Array,
  keys: string[],
): FindingSnapshot;
"#,
    );
    out
}
