//! `cargo xtask wire-js` — render the official JS wire surface from `ssc-wire`'s
//! machine-readable schema (granularity-spine Appendix A §A.4).
//!
//! Writes three do-not-edit files into `crates/wasm/js/`:
//! - `findings.generated.js` — the frozen schema object plus derived lookup
//!   tables (constants and code/digest/dependency maps);
//! - `findings.generated.d.ts` — the wire string unions and digest types;
//! - `findings.d.ts` — the public decoder/reconciler API declaration.
//!
//! The reviewed algorithm lives in the hand-written `findings.js`, which imports
//! from `findings.generated.js` and copies no numeric constant or table. Output
//! is deterministic (no timestamps), so running twice is a no-op.

use std::fs;
use std::path::Path;

use ssc_wire::schema::{schema, WireSchema};

const BANNER: &str =
    "// @generated by `cargo xtask wire-js` from ssc-wire's schema. DO NOT EDIT.\n// The reviewed decoder/reconciler lives in the hand-written findings.js.\n";

/// Render and write the three generated files. Returns the number of files whose
/// content changed (0 == the determinism no-op).
pub fn run(wasm_js_dir: &Path) -> usize {
    fs::create_dir_all(wasm_js_dir).expect("create crates/wasm/js");
    let s = schema();

    let files = [
        ("findings.generated.js", render_generated_js(&s)),
        ("findings.generated.d.ts", render_generated_dts(&s)),
        ("findings.d.ts", render_public_dts()),
    ];

    let mut changed = 0;
    for (name, content) in files {
        let path = wasm_js_dir.join(name);
        let existing = fs::read_to_string(&path).ok();
        if existing.as_deref() == Some(content.as_str()) {
            println!("unchanged: {}", path.display());
        } else {
            fs::write(&path, &content).expect("write generated file");
            println!("wrote:     {}", path.display());
            changed += 1;
        }
    }
    changed
}

fn render_generated_js(s: &WireSchema) -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push('\n');

    // The canonical schema object, embedded verbatim (JSON is valid JS).
    out.push_str("export const WIRE_SCHEMA = Object.freeze(\n");
    out.push_str(&ssc_wire::schema::schema_json());
    out.push_str("\n);\n\n");

    // Header constants + offsets + flag bits, from the one schema source.
    let o = &s.offsets;
    let fb = &s.flag_bits;
    out.push_str(&format!(
        "export const HEADER = Object.freeze({{\n  MAGIC: {magic:?},\n  VERSION: {ver},\n  RECORD_LEN: {rlen},\n  HEADER_LEN: {hlen},\n  OFFSETS: Object.freeze({{\n    headerFlags: {hf},\n    count: {cnt},\n    reserved: {res},\n    targetContextId: {tcid},\n    analysisId: {aid},\n    recordCode: {rc},\n    recordFlags: {rf},\n    recordKeyIdx: {rk},\n    recordStart: {rs},\n    recordEnd: {re},\n    recordScore: {rsc},\n    recordPayload: {rp},\n  }}),\n  FLAGS: Object.freeze({{\n    headerHasReference: {hhr},\n    severityMask: {sm},\n    hasScore: {hs},\n    hasArgs: {ha},\n    payloadSaturated: {ps},\n    recordReservedMask: {rrm},\n  }}),\n}});\n\n",
        magic = s.magic,
        ver = s.version,
        rlen = s.record_len,
        hlen = s.header_len,
        hf = o.header_flags,
        cnt = o.header_count,
        res = o.header_reserved,
        tcid = o.header_target_context_id,
        aid = o.header_analysis_id,
        rc = o.record_code,
        rf = o.record_flags,
        rk = o.record_key_idx,
        rs = o.record_start,
        re = o.record_end,
        rsc = o.record_score,
        rp = o.record_payload,
        hhr = fb.header_has_reference,
        sm = fb.record_severity_mask,
        hs = fb.record_has_score,
        ha = fb.record_has_args,
        ps = fb.record_payload_saturated,
        rrm = fb.record_reserved_mask,
    ));

    // Severities (index == numeric encoding).
    let sev = s
        .severities
        .iter()
        .map(|(_, name)| format!("{name:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!("export const SEVERITIES = Object.freeze([{sev}]);\n\n"));

    // Derived lookup tables (all from schema.rules, sorted by code).
    let code_to_rule = s
        .rules
        .iter()
        .map(|r| format!("  \"{}\": {:?},", r.code, r.rule_id))
        .collect::<Vec<_>>()
        .join("\n");
    out.push_str(&format!(
        "export const CODE_TO_RULE = Object.freeze({{\n{code_to_rule}\n}});\n\n"
    ));

    let rule_to_code = s
        .rules
        .iter()
        .map(|r| format!("  {:?}: {},", r.rule_id, r.code))
        .collect::<Vec<_>>()
        .join("\n");
    out.push_str(&format!(
        "export const RULE_TO_CODE = Object.freeze({{\n{rule_to_code}\n}});\n\n"
    ));

    let code_to_digest = s
        .rules
        .iter()
        .map(|r| format!("  \"{}\": {:?},", r.code, r.digest))
        .collect::<Vec<_>>()
        .join("\n");
    out.push_str(&format!(
        "export const CODE_TO_DIGEST = Object.freeze({{\n{code_to_digest}\n}});\n\n"
    ));

    let code_to_dep = s
        .rules
        .iter()
        .map(|r| format!("  \"{}\": {:?},", r.code, r.input_dependency))
        .collect::<Vec<_>>()
        .join("\n");
    out.push_str(&format!(
        "export const CODE_TO_INPUT_DEPENDENCY = Object.freeze({{\n{code_to_dep}\n}});\n"
    ));

    out
}

fn render_generated_dts(s: &WireSchema) -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push('\n');

    let rule_union = s
        .rules
        .iter()
        .map(|r| format!("  | {:?}", r.rule_id))
        .collect::<Vec<_>>()
        .join("\n");
    out.push_str(&format!("export type WireRuleId =\n{rule_union};\n\n"));

    out.push_str("export type Severity = \"error\" | \"warning\" | \"info\";\n\n");
    out.push_str(
        "export type InputDependency =\n  | \"target-only\"\n  | \"target-and-reference-silent-when-absent\";\n\n",
    );
    out.push_str("export type DigestShape = \"none\" | \"count-pair\" | \"u32\";\n\n");
    out.push_str(
        "/** The 4-byte per-code payload, interpreted by the record's rule. */\nexport type Digest =\n  | { shape: \"none\" }\n  | { shape: \"count-pair\"; a: number; b: number; saturated: boolean }\n  | { shape: \"u32\"; value: number };\n\n",
    );

    out.push_str("export interface SchemaRule {\n  code: number;\n  rule_id: WireRuleId;\n  digest: DigestShape;\n  input_dependency: InputDependency;\n}\n\n");
    out.push_str("export interface WireSchema {\n  magic: string;\n  version: number;\n  record_len: number;\n  header_len: number;\n  offsets: Record<string, number>;\n  flag_bits: Record<string, number>;\n  severities: Array<[number, Severity]>;\n  rules: SchemaRule[];\n}\n\n");

    out.push_str("export declare const WIRE_SCHEMA: WireSchema;\n");
    out.push_str("export declare const HEADER: {\n  MAGIC: string;\n  VERSION: number;\n  RECORD_LEN: number;\n  HEADER_LEN: number;\n  OFFSETS: Record<string, number>;\n  FLAGS: Record<string, number>;\n};\n");
    out.push_str("export declare const SEVERITIES: readonly Severity[];\n");
    out.push_str("export declare const CODE_TO_RULE: Readonly<Record<number, WireRuleId>>;\n");
    out.push_str("export declare const RULE_TO_CODE: Readonly<Record<WireRuleId, number>>;\n");
    out.push_str("export declare const CODE_TO_DIGEST: Readonly<Record<number, DigestShape>>;\n");
    out.push_str(
        "export declare const CODE_TO_INPUT_DEPENDENCY: Readonly<Record<number, InputDependency>>;\n",
    );
    out
}

fn render_public_dts() -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push('\n');
    out.push_str(
        r#"import type {
  WireRuleId,
  Severity,
  InputDependency,
  Digest,
} from "./findings.generated.js";

/** One decoded finding. Addressed by `sid` (the resolved key string), never by
 * the ephemeral wire `key_idx`, so an object survives address rebasing. */
export interface DecodedFinding {
  sid: string;
  code: WireRuleId;
  severity: Severity;
  /** UTF-16 code-unit offset into the verse text. */
  start: number;
  /** UTF-16 code-unit offset (exclusive). */
  end: number;
  score: number | null;
  hasArgs: boolean;
  digest: Digest;
  inputDependency: InputDependency;
}

/** A complete decoded snapshot. `findings[i]` corresponds to wire record `i`
 * under `analysisId` (the snapshot-private lazy-args locator). */
export interface FindingSnapshot {
  analysisId: bigint;
  targetContextId: bigint;
  hasReference: boolean;
  provenance: "live" | "reference-removed";
  findings: DecodedFinding[];
}

export interface ExpectedAnalysisIdentity {
  analysisId: bigint;
  targetContextId: bigint;
  hasReference: boolean;
}

/** Decode a packed buffer, resolving each record's `key_idx` through `keys`.
 * Throws on any malformed/unsupported buffer or out-of-range key index. */
export declare function decodeFindings(
  bytes: Uint8Array,
  keys: string[],
): FindingSnapshot;

/** Fail-closed application-cache decode. Accepts an exact identity triple
 * match, or the single saved-reference-present -> current-reference-absent
 * salvage (matching target-context id) that filters
 * `target-and-reference-silent-when-absent` rows with dense reindexing. */
export declare function decodePersistedFindings(
  bytes: Uint8Array,
  keys: string[],
  expectedIdentity: ExpectedAnalysisIdentity,
): FindingSnapshot;

/** Reconcile a new complete snapshot against a previous one, preserving object
 * identity for visibly-unchanged findings (returns the exact prior array when
 * nothing visible changed). */
export declare function reconcileFindings(
  previousSnapshot: FindingSnapshot,
  bytes: Uint8Array,
  keys: string[],
): FindingSnapshot;
"#,
    );
    out
}
