[package]
name = "ssc-core"
version.workspace = true
edition.workspace = true

[dependencies]
unicode-segmentation = { workspace = true }
unicode-normalization = { workspace = true }
icu_segmenter = { workspace = true }
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[features]
serde = ["dep:serde", "dep:serde_json"]
